
jobs: 20
latency-wait: 60
restart-times: 3
keep-going: True
cluster: "sbatch -t {resources.time_min} --mem {resources.mem_mb} -c {resources.cpus} --nodes {resources.nodes} -n {resources.nodes} -p {resources.partition} {resources.extra} -o Logs/{rule}_%j.log -e Logs/{rule}_%j.log --parsable"
cluster-status: "Slurm/status.py"
default-resources: [cpus=1, mem_mb=1000, time_min=60, nodes=1, partition=single, extra='']
